platform :ios, '7.0'
pod 'PureLayout'
pod 'UIView+Positioning'
pod 'MZFormSheetController'
pod 'NSDate-Escort'
pod 'AsyncImageView'
pod 'JMMarkSlider'
pod 'GDIIndexBar', :git => 'https://github.com/donald-pinckney/GDIIndexBar.git'
pod 'AFNetworking', '~> 2.0'
pod 'JTSImageViewController'
