devices(["iPhone 17 Pro Max"])
languages(["en-US"])

scheme("The Blue Alliance")
configuration("Debug-Screenshots")
test_target_name("TBAScreenshotUITests")

output_directory("./fastlane/screenshots")
clear_previous_screenshots(true)
override_status_bar(true)
concurrent_simulators(false)
stop_after_first_error(true)

xcargs("-skipPackagePluginValidation")
