name: On push

on:
  push:
    branches:
      - main

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    with:
      run-tests: ${{ !contains(github.event.head_commit.message, '[clowntown]') }}
      save-caches: true
    secrets: inherit
